apiVersion: apps/v1
kind: Deployment
metadata:
  name: labbox-ephys-ephys1-deployment
  labels:
    app: labbox-ephys-ephys1
spec:
  replicas: 1
  selector:
    matchLabels:
        app: labbox-ephys-ephys1
  template:
    metadata:
      labels:
        app: labbox-ephys-ephys1
    spec:
      volumes:
        - name: labbox-ephys-ephys1-pv-storage
          persistentVolumeClaim:
            claimName: pvc-labbox-ephys-ephys1-b
      containers:
      - name: labbox-ephys-ephys1
        image: magland/labbox-ephys:0.4.4
        imagePullPolicy: Always
        env:
        - name: HOME
          value: /tmp
        - name: KACHERY_P2P_START_DAEMON_OPTS
          value: --port 14207 --host xxxxxx
        - name: LABBOX_CONFIG_URI
          value: xxxxxx
        ports:
        - containerPort: 15310
        volumeMounts:
          - mountPath: "/data"
            name: labbox-ephys-ephys1-pv-storage
